databases:
  - name: auto-servis-database
    plan: free
    databaseName: bregmotors

services:
  - type: web
    name: auto-servis-backend
    runtime: docker
    plan: free
    dockerfilePath: ./backend/backend.dockerfile
    dockerContext: ./backend
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_HOST
        fromDatabase:
          name: auto-servis-database
          property: host
      - key: SPRING_DATASOURCE_PORT
        fromDatabase:
          name: auto-servis-database
          property: port
      - key: SPRING_DATASOURCE_DATABASE
        fromDatabase:
          name: auto-servis-database
          property: database
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: auto-servis-database
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: auto-servis-database
          property: password
      - key: SPRING_APPLICATION_NAME
        value: backend
      - key: SPRING_JPA_SHOW_SQL
        value: "false"
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: FRONTEND_URL
        fromService:
          type: web
          name: auto-servis-frontend
          property: host
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
    healthCheckPath: /api/health

  - type: web
    name: auto-servis-frontend
    runtime: docker
    plan: free
    dockerfilePath: ./frontend/frontend.dockerfile
    dockerContext: ./frontend
    envVars:
      - key: BACKEND_URL
        fromService:
          type: web
          name: auto-servis-backend
          property: host
      - key: PORT
        value: 80
    healthCheckPath: /health
